version: '3.3'

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.99.99.0/24
          gateway: 10.99.99.1

services:
  nginx:
    container_name: nginx
    image: lscr.io/linuxserver/nginx
    restart: unless-stopped
    networks:
      net:
        aliases: []
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${PWD}/config/nginx/snippets:/config/nginx/snippets
      - ${PWD}/config/nginx/site-confs:/config/nginx/site-confs
      - ${PWD}/config/nginx/keys:/config/nginx/keys
    environment:
      TZ: 'Asia/Shanghai'
      DOCKER_MODS: 'linuxserver/mods:nginx-proxy-confs'

  authelia:
    container_name: authelia
    image: authelia/authelia
    restart: unless-stopped
    networks:
      net:
        aliases: []
    expose:
      - 9091
    volumes:
      - ${PWD}/config/authelia:/config
    environment:
      TZ: 'Asia/Shanghai'

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ${PWD}/data/redis:/data
    networks:
      net:
        aliases: []
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - Asia/Shanghai

  traefik:
    image: traefik:v2.9.6
    container_name: traefik
    volumes:
      - ${PWD}/data/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      net:
        aliases: []
    ports:
      - 8088:80
      - 8080:8080
      - 666:443
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
    #   - '--providers.docker.exposedByDefault=false'
    #   - '--entrypoints.http=true'
    #   - '--entrypoints.http.address=:80'
    #   - '--entrypoints.http.http.redirections.entrypoint.to=https'
    #   - '--entrypoints.http.http.redirections.entrypoint.scheme=https'
    #   - '--entrypoints.https=true'
    #   - '--entrypoints.https.address=:443'
    #   - '--certificatesResolvers.letsencrypt.acme.email=your-email@your-domain.com'
    #   - '--certificatesResolvers.letsencrypt.acme.storage=/etc/traefik/acme.json'
    #   - '--certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=http'
    #   - '--log=true'
    #   - '--log.level=DEBUG'

  secure:
    container_name: secure
    image: docker.io/traefik/whoami
    restart: unless-stopped
    networks:
      net:
        aliases: []
    expose:
      - 80
    environment:
      TZ: 'Asia/Shanghai'

  public:
    container_name: public
    image: docker.io/traefik/whoami
    restart: unless-stopped
    networks:
      net:
        aliases: []
    expose:
      - 80
    environment:
      TZ: 'Asia/Shanghai'

